spring.application.name=ofertacomercial
# Configuración del servidor
server.port=8080

# Configuración de la Base de Datos MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/ofertacomercial?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=1234
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Configuración de JPA/Hibernate
# Opciones comunes:
# update: actualiza el esquema si existen cambios en las entidades (recomendado para desarrollo)
# create: elimina y recrea el esquema (borra datos existentes!)
# none: no hace nada (recomendado para producción)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true